# Generated by Django 5.2.1 on 2025-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
