# Generated by Django 5.2.1 on 2025-05-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_filme_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
