# Generated by Django 5.2.1 on 2025-05-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_filme_usuario_que_curtiram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='usuario_que_curtiram',
            new_name='usuarios_que_curtiram',
        ),
    ]
